name: build image and push to dockerhub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/deploy-demo:latest \
                        -t ${{ secrets.DOCKER_USERNAME }}/deploy-demo:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/deploy-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/deploy-demo:${{ github.sha }}
      - name: clone ops-repo and change the image
        env:
          OPS_TOKEN: ${{ secrets.OPS_REPO_TOKEN }}
        run: |
          git clone https://github.com/Raghvendra9402/ops-repo.git
          cd ops-repo

          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/deploy-demo:.*|image: ${{ secrets.DOCKER_USERNAME }}/deploy-demo:${{ github.sha }}|" deployment.yml

          git config user.name "Github Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Updated the server image tags to ${{ github.sha }}"
          git push https://${OPS_TOKEN}@github.com/Raghvendra9402/ops-repo.git main
